// Copyright 2016 Altera Corporation. All rights reserved.
// Altera products are protected under numerous U.S. and foreign patents, 
// maskwork rights, copyrights and other intellectual property laws.  
//
// This reference design file, and your use thereof, is subject to and governed
// by the terms and conditions of the applicable Altera Reference Design 
// License Agreement (either as signed by you or found at www.altera.com).  By
// using this reference design file, you indicate your acceptance of such terms
// and conditions between you and Altera Corporation.  In the event that you do
// not agree with such terms and conditions, you may not use the reference 
// design file and please promptly destroy any copies you have made.
//
// This reference design file is being provided on an "as-is" basis and as an 
// accommodation and therefore all warranties, representations or guarantees of 
// any kind (whether express, implied or statutory) including, without 
// limitation, warranties of merchantability, non-infringement, or fitness for
// a particular purpose, are specifically disclaimed.  By making this reference
// design file available, Altera expressly does not recommend, suggest or 
// require that this reference design file be used in combination with any 
// other product not provided by Altera.
/////////////////////////////////////////////////////////////////////////////


`timescale 1ps/1ps

// DESCRIPTION
// Register based synchronizer of width 1.
// Generated by one of Gregg's toys.   Share And Enjoy.

module alt_sync1r1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input din_clk,
    input [0:0] din,
    input dout_clk,
    output [0:0] dout
);

// set of handy SDC constraints
localparam MULTI_2 = "-name SDC_STATEMENT \"set_multicycle_path -to [get_keepers *alt_sync1r1*ff_meta\[*\]] 2\" ";
localparam MULTI_3 = "-name SDC_STATEMENT \"set_multicycle_path -to [get_keepers *alt_sync1r1*ff_meta\[*\]] 3\" ";
localparam FPATH = "-name SDC_STATEMENT \"set_false_path -to [get_keepers *alt_sync1r1*ff_meta\[*\]]\" ";
localparam FHOLD = "-name SDC_STATEMENT \"set_false_path -hold -to [get_keepers *alt_sync1r1*ff_meta\[*\]]\" ";

reg [0:0] ff_launch = 1'b0 /* synthesis preserve dont_replicate */;
always @(posedge din_clk) begin
	ff_launch <= din;
end

localparam SDC = FPATH;
(* altera_attribute = SDC *)
reg [0:0] ff_meta = 1'b0 /* synthesis preserve dont_replicate */;
always @(posedge dout_clk) begin
	ff_meta <= ff_launch;
end

reg [0:0] ff_sync = 1'b0 /* synthesis preserve dont_replicate */;
always @(posedge dout_clk) begin
	ff_sync <= ff_meta;
end

assign dout = ff_sync;
endmodule

